const state = { complaints: [], analytics: null };
const $ = (id) => document.getElementById(id);
document.querySelectorAll("[data-section]").forEach((button) => button.addEventListener("click", () => showSection(button.dataset.section)));
$("analyzeButton").addEventListener("click", analyzeComplaint);
$("clearButton").addEventListener("click", clearComplaint);
$("copyButton").addEventListener("click", async () => { await navigator.clipboard.writeText($("generatedReply").innerText); $("copyButton").textContent = "Copied"; setTimeout(() => { $("copyButton").textContent = "Copy reply"; }, 1500); });
function showSection(sectionId) { document.querySelectorAll(".section").forEach((section) => section.classList.toggle("active-section", section.id === sectionId)); document.querySelectorAll(".nav-button").forEach((button) => button.classList.toggle("active", button.dataset.section === sectionId)); }
async function loadWorkspace() { const [complaintsResponse, analyticsResponse] = await Promise.all([fetch("/complaints"), fetch("/analytics")]); state.complaints = await complaintsResponse.json(); state.analytics = await analyticsResponse.json(); renderDashboard(); renderAnalytics(); }
function renderDashboard() { const metrics = state.analytics; $("totalComplaints").textContent = metrics.total; $("highComplaints").textContent = metrics.high_priority; $("pendingComplaints").textContent = metrics.pending; $("resolvedComplaints").textContent = metrics.resolved; $("complaintTable").innerHTML = state.complaints.slice(0, 8).map((item) => `<tr><td class="case-id">#${String(item.id).padStart(3, "0")}</td><td>${escapeHtml(item.complaint)}</td><td><span class="tag">${item.category}</span></td><td><span class="priority ${item.urgency.toLowerCase()}">${item.urgency}</span></td><td>${item.department}</td></tr>`).join(""); renderBars($("categoryBars"), metrics.by_category, "teal"); }
function renderAnalytics() { renderBars($("urgencyBars"), state.analytics.by_urgency, "coral"); renderBars($("departmentBars"), state.analytics.by_department, "gold"); const top = Object.entries(state.analytics.by_category).sort((a, b) => b[1] - a[1])[0]; $("insightText").textContent = top ? `${top[0]} is your most common case type, accounting for ${top[1]} of ${state.analytics.total} complaints.` : "No complaint signal yet."; }
function renderBars(container, values, color) { const maximum = Math.max(...Object.values(values), 1); container.innerHTML = Object.entries(values).sort((a, b) => b[1] - a[1]).map(([label, value]) => `<div class="bar-row"><div><span>${label}</span><b>${value}</b></div><div class="bar-track"><i class="bar-${color}" style="width:${(value / maximum) * 100}%"></i></div></div>`).join(""); }
async function analyzeComplaint() { const complaint = $("complaintInput").value.trim(); if (complaint.length < 3) { $("errorMessage").textContent = "Add a little more detail before analyzing."; return; } $("errorMessage").textContent = ""; $("analysisState").textContent = "Analyzing..."; $("analyzeButton").disabled = true; const response = await fetch("/submit-complaint", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ complaint_text: complaint, customer_name: $("customerName").value.trim() || "Customer" }) }); const result = await response.json(); $("resultCategory").textContent = result.category; $("resultUrgency").textContent = result.urgency; $("resultDepartment").textContent = result.department; $("resultSummary").textContent = result.summary; $("resultAction").textContent = result.suggested_action; $("generatedReply").textContent = result.reply; $("analysisState").textContent = "Analysis complete"; $("analyzeButton").disabled = false; await loadWorkspace(); }
function clearComplaint() { ["customerName", "complaintInput"].forEach((id) => $(id).value = ""); ["resultCategory", "resultUrgency", "resultDepartment"].forEach((id) => $(id).textContent = "—"); $("resultSummary").textContent = "Your analysis will appear here."; $("resultAction").textContent = "—"; $("generatedReply").textContent = "Analyze a complaint to draft a thoughtful response."; $("analysisState").textContent = "Waiting for a case"; }
function escapeHtml(value) { return value.replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" }[character])); }
loadWorkspace().catch(() => { if ($("errorMessage")) $("errorMessage").textContent = "The workspace could not be reached. Start the FastAPI server and refresh."; });